### ISSUE TITLE
Problem at Running aed on manjaro

### ISSUE THREAD

**Issue by CaptainK1ll** [Ruunyox/aed#1]
error code:

Traceback (most recent call last):
  File "/usr/bin/aed", line 33, in <module>
    sys.exit(load_entry_point('aed==1.0', 'console_scripts', 'aed')())
  File "/usr/lib/python3.10/site-packages/aed/bin/__main__.py", line 40, in main
    ac = AlacrittyContainer(ALACRITTY_CONFIG, ALACRITTY_COLOR_DIR, ALACRITTY_FONT_DIR)
  File "/usr/lib/python3.10/site-packages/aed/container/alacritty_container.py", line 158, in __init__
    self.alacritty_config = AlacrittyContainer.load_yaml(self.config_fn)
  File "/usr/lib/python3.10/site-packages/aed/container/alacritty_container.py", line 236, in load_yaml
    with open(config_fn, "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kalinux/.config/alacritty/alacritty.yml'

**Comment by nec4** [comment]
Hello - the editor expects to see your alacritty config in `$HOME/.config/alacritty/alacritty.yml`. Where is your alacritty config located?

**Comment by CaptainK1ll** [comment]
Oh thx i did not place the config file there sry for the disturbance ^^

Von meinem iPhone gesendet

Am 03.10.2022 um 00:02 schrieb nec4 ***@***.***>:

﻿

Hello - the editor expects to see your alacritty config in $HOME/.config/alacritty/alacritty.yml. Where is your alacritty config located?
